version: '3'
services:
  file-zip-on-demand:
    container_name: file-zip-on-demand
    build: .
    expose:
      - 4000
    ports:
      - "4000:4000"
    command: sh -c "yarn && yarn dev:server"
    volumes:
      - "./:/usr/src/app"
      - "reserved:/usr/src/app/node_modules"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 300M
volumes:
  reserved: null
