export const small = [
  {
    id: '1',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/bla-nome.png',
    name: 'bla-nome.png',
    mimeType: 'image/png',
  },
  {
    id: '2',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/foo-nome.png',
    name: 'foo-nome.png',
    mimeType: 'image/png',
  },
];

export const medium = [
  {
    id: '1',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/bla-nome.png',
    name: 'bla-nome.png',
    mimeType: 'image/png',
  },
  {
    id: '2',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/foo-nome.png',
    name: 'foo-nome.png',
    mimeType: 'image/png',
  },
  {
    id: '3',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-four.pdf',
    name: 'large-file-four.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '4',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-three.pdf',
    name: 'large-file-three.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '5',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-two.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '6',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file.pdf',
    name: 'large-file.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '7',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/nome-bar.jpg',
    name: 'nome-bar.jpg',
    mimeType: 'image/jpeg',
  },
  {
    id: '8',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/nome-bla.png',
    name: 'nome-bla.png',
    mimeType: 'image/png',
  },
  {
    id: '9',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/nome-foo.png',
    name: 'nome-foo.png',
    mimeType: 'image/png',
  },
  {
    id: '10',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/tmj.mp4',
    name: 'tmj.mp4',
    mimeType: 'video/mp4',
  },
];

export const large = [
  {
    id: '1',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/bla-nome.png',
    name: 'bla-nome.png',
    mimeType: 'image/png',
  },
  {
    id: '2',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/foo-nome.png',
    name: 'foo-nome.png',
    mimeType: 'image/png',
  },
  {
    id: '3',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-four.pdf',
    name: 'large-file-four.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '4',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-three.pdf',
    name: 'large-file-three.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '5',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-two.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '6',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file.pdf',
    name: 'large-file.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '7',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/nome-bar.jpg',
    name: 'nome-bar.jpg',
    mimeType: 'image/jpeg',
  },
  {
    id: '8',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/nome-bla.png',
    name: 'nome-bla.png',
    mimeType: 'image/png',
  },
  {
    id: '9',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/nome-foo.png',
    name: 'nome-foo.png',
    mimeType: 'image/png',
  },
  {
    id: '10',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/tmj.mp4',
    name: 'tmj.mp4',
    mimeType: 'video/mp4',
  },
  {
    id: '11',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-five.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '12',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-six.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '13',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-seven.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '14',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-eight.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '15',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-nine.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '16',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-ten.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '17',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-eleven.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '18',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-twelve.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '19',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-thirteen.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '20',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-fourteen.pdf',
    mimeType: 'application/pdf',
  },
];

export const extraLarge = [
  {
    id: '1',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/bla-nome.png',
    name: 'bla-nome.png',
    mimeType: 'image/png',
  },
  {
    id: '2',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/foo-nome.png',
    name: 'foo-nome.png',
    mimeType: 'image/png',
  },
  {
    id: '3',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-four.pdf',
    name: 'large-file-four.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '4',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-three.pdf',
    name: 'large-file-three.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '5',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-two.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '6',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file.pdf',
    name: 'large-file.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '7',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/nome-bar.jpg',
    name: 'nome-bar.jpg',
    mimeType: 'image/jpeg',
  },
  {
    id: '8',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/nome-bla.png',
    name: 'nome-bla.png',
    mimeType: 'image/png',
  },
  {
    id: '9',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/nome-foo.png',
    name: 'nome-foo.png',
    mimeType: 'image/png',
  },
  {
    id: '10',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/tmj.mp4',
    name: 'tmj.mp4',
    mimeType: 'video/mp4',
  },
  {
    id: '11',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-five.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '12',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-six.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '13',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-seven.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '14',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-eight.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '15',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-nine.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '16',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-ten.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '17',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-eleven.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '18',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-twelve.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '19',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-thirteen.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '20',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-fourteen.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '21',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-twenty-one.pdf',
    mimeType: 'image/png',
  },
  {
    id: '22',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-twenty-two.pdf',
    mimeType: 'image/png',
  },
  {
    id: '23',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-twenty-three.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '24',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-twenty-four.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '25',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-twenty-five.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '26',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-twenty-six.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '27',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-twenty-seven.pdf',
    mimeType: 'image/jpeg',
  },
  {
    id: '28',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-twenty-eight.pdf',
    mimeType: 'image/png',
  },
  {
    id: '29',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-twenty-nine.pdf',
    mimeType: 'image/png',
  },
  {
    id: '30',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-thirty.pdf',
    mimeType: 'video/mp4',
  },
  {
    id: '31',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-thirty-one.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '32',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-thirty-two.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '33',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-thirty-three.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '34',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-thirty-four.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '35',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-thirty-five.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '36',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-thirty-six.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '37',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-thirty-seven.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '38',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-thirty-eight.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '39',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-thirty-nine.pdf',
    mimeType: 'application/pdf',
  },
  {
    id: '40',
    url: 'https://my-temp-s3.s3.sa-east-1.amazonaws.com/large-file-two.pdf',
    name: 'large-file-forty.pdf',
    mimeType: 'application/pdf',
  },
];
